fix block grid size
julienkay/SNeRG-Unity-Viewer pull request #4
Opened 2023-05-19 07:51 UTC by 54way

![image](https://github.com/julienkay/SNeRG-Unity-Viewer/assets/21360297/b8a2564c-a6cb-48b7-9438-9c7b5783e847)
![image](https://github.com/julienkay/SNeRG-Unity-Viewer/assets/21360297/e7ef8865-be27-49d5-bb2a-e1c5c59decd5)
![image](https://github.com/julienkay/SNeRG-Unity-Viewer/assets/21360297/4ff544ce-5b3c-43e9-a259-c1054b3412dd)

2023-05-27 22:13 UTC, julienkay commented
Hi :)

thanks a lot for this PR and for flagging the issue! It seems I've introduced a bug with some recent changes with the intent of getting rid of Unity's shader warnings regarding the usage of integer divides ("integer divides may be much slower, try using uints if possible.")

I'd like to keep using floats so I've proposed a little change that I think would be a good fix. If you don't mind accepting I'll merge this PR.

Regarding the changes to the volume size calculations: I'm not strictly against the changes, but they seem to produce similar/the same results as the original code. Were there any scenes that gave you issues?

2023-05-27 23:10 UTC, julienkay requested changes

2023-05-27 23:10 UTC, julienkay commented on Editor/RaymarchShader.cs
> +                    half3 blockGridSize = half3(iBlockGridSize);
```suggestion
                    float3 iBlockGridBlocks = floor((gridSize + blockSize - 1) / blockSize);
                    float3 blockGridSize = iBlockGridBlocks * blockSize;
```

The issue I've introduced was that iBlockGridBlocks should be a vector, not a scalar. The suggestion should bring back the correct behavior while still using float math, therefore not throwing warnings in Unity.

2023-05-31 02:47 UTC, 54way commented
Hi~ 
Sorry for replying late. Recently I've got sick for 6 days, but I I'm feeling better now.
I don't mind keeping using floats and making a better changes.
About the colume size caculation, toycar scene and spheres scene are cut by small volume which size is not big enough because te centroid of the volume does not necessarily coincide with the origin of the object's coordinate system.
![toycar](https://github.com/julienkay/SNeRG-Unity-Viewer/assets/21360297/5ea5a1d5-7da6-481f-950f-1a4d4bd809ce)
![spheres](https://github.com/julienkay/SNeRG-Unity-Viewer/assets/21360297/8b0472c7-723c-4dc2-9aa1-b2e0c7cde048)

2023-06-01 11:51 UTC, julienkay commented
>About the colume size caculation, toycar scene and spheres scene are cut by small volume which size is not big enough because the centroid of the volume does not necessarily coincide with the origin of the object's coordinate system.
I see, you're completely right. Thanks for this contribution! Let me reopen the PR and merge this.

2023-06-01 11:51 UTC, merged